// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type MenuCreate = {
    parent_id?: (string | null);
    path: string;
    title_zh: string;
    title_en: string;
    icon?: (string | null);
    sort_order?: number;
    is_active?: boolean;
    required_permission_code?: (string | null);
};

export type MenuPublic = {
    id: string;
    parent_id?: (string | null);
    path: string;
    title_zh: string;
    title_en: string;
    icon?: (string | null);
    sort_order?: number;
    is_active?: boolean;
    required_permission_code?: (string | null);
};

export type MenuRoleIds = {
    role_ids?: Array<(string)>;
};

export type MenuRolesPublic = {
    data: Array<RolePublic>;
    count: number;
};

export type MenusPublic = {
    data: Array<MenuPublic>;
    count: number;
};

export type MenusTreePublic = {
    data: Array<MenuTreePublic>;
    count: number;
};

export type MenuTreePublic = {
    id: string;
    parent_id?: (string | null);
    path: string;
    title_zh: string;
    title_en: string;
    icon?: (string | null);
    sort_order?: number;
    is_active?: boolean;
    required_permission_code?: (string | null);
    children?: Array<MenuTreePublic>;
};

export type MenuUpdate = {
    parent_id?: (string | null);
    path?: (string | null);
    title_zh?: (string | null);
    title_en?: (string | null);
    icon?: (string | null);
    sort_order?: (number | null);
    is_active?: (boolean | null);
    required_permission_code?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PermissionPublic = {
    id: string;
    code: string;
    name: string;
};

export type PermissionsPublic = {
    data: Array<PermissionPublic>;
    count: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RoleCreate = {
    name: string;
    description?: (string | null);
};

export type RolePermissionIds = {
    permission_ids?: Array<(string)>;
};

export type RolePublic = {
    id: string;
    name: string;
    description?: (string | null);
    is_system?: boolean;
};

export type RolesWithPermissionsPublic = {
    data: Array<RoleWithPermissions>;
    count: number;
};

export type RoleUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type RoleWithPermissions = {
    id: string;
    name: string;
    description?: (string | null);
    is_system?: boolean;
    permissions?: Array<PermissionPublic>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
    roles?: Array<(string)>;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserRoleIds = {
    role_ids?: Array<(string)>;
};

export type UserRolesPublic = {
    data: Array<RolePublic>;
    count: number;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MenusReadMenusMeResponse = (MenusTreePublic);

export type MenusReadMenusAdminResponse = (MenusPublic);

export type MenusCreateMenuData = {
    requestBody: MenuCreate;
};

export type MenusCreateMenuResponse = (MenuPublic);

export type MenusReadMenuRolesData = {
    menuId: string;
};

export type MenusReadMenuRolesResponse = (MenuRolesPublic);

export type MenusUpdateMenuRolesData = {
    menuId: string;
    requestBody: MenuRoleIds;
};

export type MenusUpdateMenuRolesResponse = (Message);

export type MenusUpdateMenuData = {
    menuId: string;
    requestBody: MenuUpdate;
};

export type MenusUpdateMenuResponse = (MenuPublic);

export type MenusDeleteMenuData = {
    menuId: string;
};

export type MenusDeleteMenuResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RbacReadPermissionsResponse = (PermissionsPublic);

export type RbacReadRolesResponse = (RolesWithPermissionsPublic);

export type RbacCreateRoleData = {
    requestBody: RoleCreate;
};

export type RbacCreateRoleResponse = (RoleWithPermissions);

export type RbacUpdateRoleData = {
    requestBody: RoleUpdate;
    roleId: string;
};

export type RbacUpdateRoleResponse = (RoleWithPermissions);

export type RbacDeleteRoleData = {
    roleId: string;
};

export type RbacDeleteRoleResponse = (Message);

export type RbacUpdateRolePermissionsData = {
    requestBody: RolePermissionIds;
    roleId: string;
};

export type RbacUpdateRolePermissionsResponse = (RoleWithPermissions);

export type RbacReadUserRolesData = {
    userId: string;
};

export type RbacReadUserRolesResponse = (UserRolesPublic);

export type RbacUpdateUserRolesData = {
    requestBody: UserRoleIds;
    userId: string;
};

export type RbacUpdateUserRolesResponse = (UserRolesPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);