/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTargetsRouteImport } from './routes/_layout/targets'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutMetricsRouteImport } from './routes/_layout/metrics'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutEventsRouteImport } from './routes/_layout/events'
import { Route as LayoutDashboardsRouteImport } from './routes/_layout/dashboards'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin.index'
import { Route as LayoutTargetsTargetIdRouteImport } from './routes/_layout/targets.$targetId'
import { Route as LayoutNotificationsPoliciesRouteImport } from './routes/_layout/notifications.policies'
import { Route as LayoutNotificationsOncallRouteImport } from './routes/_layout/notifications.oncall'
import { Route as LayoutNotificationsLogsRouteImport } from './routes/_layout/notifications.logs'
import { Route as LayoutNotificationsChannelsRouteImport } from './routes/_layout/notifications.channels'
import { Route as LayoutDashboardsSlugRouteImport } from './routes/_layout/dashboards.$slug'
import { Route as LayoutAlertsSilencesRouteImport } from './routes/_layout/alerts.silences'
import { Route as LayoutAlertsRulesRouteImport } from './routes/_layout/alerts.rules'
import { Route as LayoutAlertsHistoryRouteImport } from './routes/_layout/alerts.history'
import { Route as LayoutAlertsActiveRouteImport } from './routes/_layout/alerts.active'
import { Route as LayoutAdminTokensRouteImport } from './routes/_layout/admin.tokens'
import { Route as LayoutAdminPermissionsRouteImport } from './routes/_layout/admin.permissions'
import { Route as LayoutAdminMenusRouteImport } from './routes/_layout/admin.menus'
import { Route as LayoutAdminAuditRouteImport } from './routes/_layout/admin.audit'
import { Route as LayoutAdminAgentsRouteImport } from './routes/_layout/admin.agents'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTargetsRoute = LayoutTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMetricsRoute = LayoutMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsRoute = LayoutEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardsRoute = LayoutDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutTargetsTargetIdRoute = LayoutTargetsTargetIdRouteImport.update({
  id: '/$targetId',
  path: '/$targetId',
  getParentRoute: () => LayoutTargetsRoute,
} as any)
const LayoutNotificationsPoliciesRoute =
  LayoutNotificationsPoliciesRouteImport.update({
    id: '/notifications/policies',
    path: '/notifications/policies',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutNotificationsOncallRoute =
  LayoutNotificationsOncallRouteImport.update({
    id: '/notifications/oncall',
    path: '/notifications/oncall',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutNotificationsLogsRoute = LayoutNotificationsLogsRouteImport.update({
  id: '/notifications/logs',
  path: '/notifications/logs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNotificationsChannelsRoute =
  LayoutNotificationsChannelsRouteImport.update({
    id: '/notifications/channels',
    path: '/notifications/channels',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutDashboardsSlugRoute = LayoutDashboardsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LayoutDashboardsRoute,
} as any)
const LayoutAlertsSilencesRoute = LayoutAlertsSilencesRouteImport.update({
  id: '/alerts/silences',
  path: '/alerts/silences',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAlertsRulesRoute = LayoutAlertsRulesRouteImport.update({
  id: '/alerts/rules',
  path: '/alerts/rules',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAlertsHistoryRoute = LayoutAlertsHistoryRouteImport.update({
  id: '/alerts/history',
  path: '/alerts/history',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAlertsActiveRoute = LayoutAlertsActiveRouteImport.update({
  id: '/alerts/active',
  path: '/alerts/active',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminTokensRoute = LayoutAdminTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminPermissionsRoute = LayoutAdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminMenusRoute = LayoutAdminMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminAuditRoute = LayoutAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminAgentsRoute = LayoutAdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => LayoutAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/dashboards': typeof LayoutDashboardsRouteWithChildren
  '/events': typeof LayoutEventsRoute
  '/items': typeof LayoutItemsRoute
  '/metrics': typeof LayoutMetricsRoute
  '/settings': typeof LayoutSettingsRoute
  '/targets': typeof LayoutTargetsRouteWithChildren
  '/admin/agents': typeof LayoutAdminAgentsRoute
  '/admin/audit': typeof LayoutAdminAuditRoute
  '/admin/menus': typeof LayoutAdminMenusRoute
  '/admin/permissions': typeof LayoutAdminPermissionsRoute
  '/admin/tokens': typeof LayoutAdminTokensRoute
  '/alerts/active': typeof LayoutAlertsActiveRoute
  '/alerts/history': typeof LayoutAlertsHistoryRoute
  '/alerts/rules': typeof LayoutAlertsRulesRoute
  '/alerts/silences': typeof LayoutAlertsSilencesRoute
  '/dashboards/$slug': typeof LayoutDashboardsSlugRoute
  '/notifications/channels': typeof LayoutNotificationsChannelsRoute
  '/notifications/logs': typeof LayoutNotificationsLogsRoute
  '/notifications/oncall': typeof LayoutNotificationsOncallRoute
  '/notifications/policies': typeof LayoutNotificationsPoliciesRoute
  '/targets/$targetId': typeof LayoutTargetsTargetIdRoute
  '/admin/': typeof LayoutAdminIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboards': typeof LayoutDashboardsRouteWithChildren
  '/events': typeof LayoutEventsRoute
  '/items': typeof LayoutItemsRoute
  '/metrics': typeof LayoutMetricsRoute
  '/settings': typeof LayoutSettingsRoute
  '/targets': typeof LayoutTargetsRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/admin/agents': typeof LayoutAdminAgentsRoute
  '/admin/audit': typeof LayoutAdminAuditRoute
  '/admin/menus': typeof LayoutAdminMenusRoute
  '/admin/permissions': typeof LayoutAdminPermissionsRoute
  '/admin/tokens': typeof LayoutAdminTokensRoute
  '/alerts/active': typeof LayoutAlertsActiveRoute
  '/alerts/history': typeof LayoutAlertsHistoryRoute
  '/alerts/rules': typeof LayoutAlertsRulesRoute
  '/alerts/silences': typeof LayoutAlertsSilencesRoute
  '/dashboards/$slug': typeof LayoutDashboardsSlugRoute
  '/notifications/channels': typeof LayoutNotificationsChannelsRoute
  '/notifications/logs': typeof LayoutNotificationsLogsRoute
  '/notifications/oncall': typeof LayoutNotificationsOncallRoute
  '/notifications/policies': typeof LayoutNotificationsPoliciesRoute
  '/targets/$targetId': typeof LayoutTargetsTargetIdRoute
  '/admin': typeof LayoutAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/dashboards': typeof LayoutDashboardsRouteWithChildren
  '/_layout/events': typeof LayoutEventsRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/metrics': typeof LayoutMetricsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/targets': typeof LayoutTargetsRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/agents': typeof LayoutAdminAgentsRoute
  '/_layout/admin/audit': typeof LayoutAdminAuditRoute
  '/_layout/admin/menus': typeof LayoutAdminMenusRoute
  '/_layout/admin/permissions': typeof LayoutAdminPermissionsRoute
  '/_layout/admin/tokens': typeof LayoutAdminTokensRoute
  '/_layout/alerts/active': typeof LayoutAlertsActiveRoute
  '/_layout/alerts/history': typeof LayoutAlertsHistoryRoute
  '/_layout/alerts/rules': typeof LayoutAlertsRulesRoute
  '/_layout/alerts/silences': typeof LayoutAlertsSilencesRoute
  '/_layout/dashboards/$slug': typeof LayoutDashboardsSlugRoute
  '/_layout/notifications/channels': typeof LayoutNotificationsChannelsRoute
  '/_layout/notifications/logs': typeof LayoutNotificationsLogsRoute
  '/_layout/notifications/oncall': typeof LayoutNotificationsOncallRoute
  '/_layout/notifications/policies': typeof LayoutNotificationsPoliciesRoute
  '/_layout/targets/$targetId': typeof LayoutTargetsTargetIdRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/dashboards'
    | '/events'
    | '/items'
    | '/metrics'
    | '/settings'
    | '/targets'
    | '/admin/agents'
    | '/admin/audit'
    | '/admin/menus'
    | '/admin/permissions'
    | '/admin/tokens'
    | '/alerts/active'
    | '/alerts/history'
    | '/alerts/rules'
    | '/alerts/silences'
    | '/dashboards/$slug'
    | '/notifications/channels'
    | '/notifications/logs'
    | '/notifications/oncall'
    | '/notifications/policies'
    | '/targets/$targetId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/dashboards'
    | '/events'
    | '/items'
    | '/metrics'
    | '/settings'
    | '/targets'
    | '/'
    | '/admin/agents'
    | '/admin/audit'
    | '/admin/menus'
    | '/admin/permissions'
    | '/admin/tokens'
    | '/alerts/active'
    | '/alerts/history'
    | '/alerts/rules'
    | '/alerts/silences'
    | '/dashboards/$slug'
    | '/notifications/channels'
    | '/notifications/logs'
    | '/notifications/oncall'
    | '/notifications/policies'
    | '/targets/$targetId'
    | '/admin'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/dashboards'
    | '/_layout/events'
    | '/_layout/items'
    | '/_layout/metrics'
    | '/_layout/settings'
    | '/_layout/targets'
    | '/_layout/'
    | '/_layout/admin/agents'
    | '/_layout/admin/audit'
    | '/_layout/admin/menus'
    | '/_layout/admin/permissions'
    | '/_layout/admin/tokens'
    | '/_layout/alerts/active'
    | '/_layout/alerts/history'
    | '/_layout/alerts/rules'
    | '/_layout/alerts/silences'
    | '/_layout/dashboards/$slug'
    | '/_layout/notifications/channels'
    | '/_layout/notifications/logs'
    | '/_layout/notifications/oncall'
    | '/_layout/notifications/policies'
    | '/_layout/targets/$targetId'
    | '/_layout/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/targets': {
      id: '/_layout/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof LayoutTargetsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/metrics': {
      id: '/_layout/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof LayoutMetricsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events': {
      id: '/_layout/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof LayoutEventsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboards': {
      id: '/_layout/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof LayoutDashboardsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/targets/$targetId': {
      id: '/_layout/targets/$targetId'
      path: '/$targetId'
      fullPath: '/targets/$targetId'
      preLoaderRoute: typeof LayoutTargetsTargetIdRouteImport
      parentRoute: typeof LayoutTargetsRoute
    }
    '/_layout/notifications/policies': {
      id: '/_layout/notifications/policies'
      path: '/notifications/policies'
      fullPath: '/notifications/policies'
      preLoaderRoute: typeof LayoutNotificationsPoliciesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notifications/oncall': {
      id: '/_layout/notifications/oncall'
      path: '/notifications/oncall'
      fullPath: '/notifications/oncall'
      preLoaderRoute: typeof LayoutNotificationsOncallRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notifications/logs': {
      id: '/_layout/notifications/logs'
      path: '/notifications/logs'
      fullPath: '/notifications/logs'
      preLoaderRoute: typeof LayoutNotificationsLogsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notifications/channels': {
      id: '/_layout/notifications/channels'
      path: '/notifications/channels'
      fullPath: '/notifications/channels'
      preLoaderRoute: typeof LayoutNotificationsChannelsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboards/$slug': {
      id: '/_layout/dashboards/$slug'
      path: '/$slug'
      fullPath: '/dashboards/$slug'
      preLoaderRoute: typeof LayoutDashboardsSlugRouteImport
      parentRoute: typeof LayoutDashboardsRoute
    }
    '/_layout/alerts/silences': {
      id: '/_layout/alerts/silences'
      path: '/alerts/silences'
      fullPath: '/alerts/silences'
      preLoaderRoute: typeof LayoutAlertsSilencesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/alerts/rules': {
      id: '/_layout/alerts/rules'
      path: '/alerts/rules'
      fullPath: '/alerts/rules'
      preLoaderRoute: typeof LayoutAlertsRulesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/alerts/history': {
      id: '/_layout/alerts/history'
      path: '/alerts/history'
      fullPath: '/alerts/history'
      preLoaderRoute: typeof LayoutAlertsHistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/alerts/active': {
      id: '/_layout/alerts/active'
      path: '/alerts/active'
      fullPath: '/alerts/active'
      preLoaderRoute: typeof LayoutAlertsActiveRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/tokens': {
      id: '/_layout/admin/tokens'
      path: '/tokens'
      fullPath: '/admin/tokens'
      preLoaderRoute: typeof LayoutAdminTokensRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/permissions': {
      id: '/_layout/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof LayoutAdminPermissionsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/menus': {
      id: '/_layout/admin/menus'
      path: '/menus'
      fullPath: '/admin/menus'
      preLoaderRoute: typeof LayoutAdminMenusRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/audit': {
      id: '/_layout/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof LayoutAdminAuditRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/agents': {
      id: '/_layout/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof LayoutAdminAgentsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminAgentsRoute: typeof LayoutAdminAgentsRoute
  LayoutAdminAuditRoute: typeof LayoutAdminAuditRoute
  LayoutAdminMenusRoute: typeof LayoutAdminMenusRoute
  LayoutAdminPermissionsRoute: typeof LayoutAdminPermissionsRoute
  LayoutAdminTokensRoute: typeof LayoutAdminTokensRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminAgentsRoute: LayoutAdminAgentsRoute,
  LayoutAdminAuditRoute: LayoutAdminAuditRoute,
  LayoutAdminMenusRoute: LayoutAdminMenusRoute,
  LayoutAdminPermissionsRoute: LayoutAdminPermissionsRoute,
  LayoutAdminTokensRoute: LayoutAdminTokensRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutDashboardsRouteChildren {
  LayoutDashboardsSlugRoute: typeof LayoutDashboardsSlugRoute
}

const LayoutDashboardsRouteChildren: LayoutDashboardsRouteChildren = {
  LayoutDashboardsSlugRoute: LayoutDashboardsSlugRoute,
}

const LayoutDashboardsRouteWithChildren =
  LayoutDashboardsRoute._addFileChildren(LayoutDashboardsRouteChildren)

interface LayoutTargetsRouteChildren {
  LayoutTargetsTargetIdRoute: typeof LayoutTargetsTargetIdRoute
}

const LayoutTargetsRouteChildren: LayoutTargetsRouteChildren = {
  LayoutTargetsTargetIdRoute: LayoutTargetsTargetIdRoute,
}

const LayoutTargetsRouteWithChildren = LayoutTargetsRoute._addFileChildren(
  LayoutTargetsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutDashboardsRoute: typeof LayoutDashboardsRouteWithChildren
  LayoutEventsRoute: typeof LayoutEventsRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutMetricsRoute: typeof LayoutMetricsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTargetsRoute: typeof LayoutTargetsRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAlertsActiveRoute: typeof LayoutAlertsActiveRoute
  LayoutAlertsHistoryRoute: typeof LayoutAlertsHistoryRoute
  LayoutAlertsRulesRoute: typeof LayoutAlertsRulesRoute
  LayoutAlertsSilencesRoute: typeof LayoutAlertsSilencesRoute
  LayoutNotificationsChannelsRoute: typeof LayoutNotificationsChannelsRoute
  LayoutNotificationsLogsRoute: typeof LayoutNotificationsLogsRoute
  LayoutNotificationsOncallRoute: typeof LayoutNotificationsOncallRoute
  LayoutNotificationsPoliciesRoute: typeof LayoutNotificationsPoliciesRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutDashboardsRoute: LayoutDashboardsRouteWithChildren,
  LayoutEventsRoute: LayoutEventsRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutMetricsRoute: LayoutMetricsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTargetsRoute: LayoutTargetsRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAlertsActiveRoute: LayoutAlertsActiveRoute,
  LayoutAlertsHistoryRoute: LayoutAlertsHistoryRoute,
  LayoutAlertsRulesRoute: LayoutAlertsRulesRoute,
  LayoutAlertsSilencesRoute: LayoutAlertsSilencesRoute,
  LayoutNotificationsChannelsRoute: LayoutNotificationsChannelsRoute,
  LayoutNotificationsLogsRoute: LayoutNotificationsLogsRoute,
  LayoutNotificationsOncallRoute: LayoutNotificationsOncallRoute,
  LayoutNotificationsPoliciesRoute: LayoutNotificationsPoliciesRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
